                                                                                                                                                                                             [keyboard]
name = "TRH34"
product_name = "TRH34"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "TRHKeyboards"
chip = "rp2040"

[matrix]
input_pins = ["PIN_6", "PIN_7", "PIN_8", "PIN_9"]
output_pins = ["PIN_20", "PIN_19", "PIN_18", "PIN_17", "PIN_16", "PIN_15", "PIN_14", "PIN_13", "PIN_12", "PIN_11"]

[layout]
rows = 4
cols = 10
layers = 4
keymap = [
    [    
        ["Q",              "W",                "E",                     "R",                      "T",                   "Y",              "U",                "I",             "O",               "P"],
        ["A",              "S",                "D",                     "F",                      "G",                   "H",              "J",                "K",             "L",               "Semicolon"],
        ["Z",              "X",                "C",                     "V",                      "B",                   "Quote",          "N",                "M",             "Comma",           "Dot"],
        ["_",             "_",               "_",                    "MO(2)",                  "Space",               "Backspace",      "MO(1)",            "_",            "_",              "_"]
    ],
    [
        ["Escape",         "SHIFTED(Grave)",   "SHIFTED(LeftBracket)",  "SHIFTED(RightBracket)",  "Grave",               "Semicolon",      "LeftBracket",      "RightBracket",  "SHIFTED(Kc9)",    "SHIFTED(Kc0)"],
        ["SHIFTED(Kc1)",   "SHIFTED(Kc2)",     "SHIFTED(Kc3)",          "SHIFTED(Kc4)",           "SHIFTED(Kc5)",        "Minus",          "_",                "_",             "_",               "_"],
        ["SHIFTED(Kc6)",   "SHIFTED(Kc7)",     "Backslash",             "Slash",                  "SHIFTED(Backslash)",  "Equal",          "SHIFTED(Equal)",   "SHIFTED(Kc8)",  "SHIFTED(Slash)",  "SHIFTED(Kc1)"],
        ["_",             "_",               "_",                    "MO(3)",                  "Space",               "Backspace",      "_",                "_",            "_",              "_"]
    ],
    [
        ["Escape",         "KbMute",          "E",                      "R",                      "_",                  "PageUp",         "Home",              "Up",            "End",             "Delete"],
        ["_",               "_",              "_",                      "_",                      "_",                  "Tab",            "Left",              "Down",          "Right",           "Enter"],
        ["KbVolumeDown",   "KbVolumeDown",    "C",                      "V",                      "B",                   "PageDown",       "_",                "_",             "_",               "_"],
        ["_",             "_",              "_",                     "_",                      "Space",               "Backspace",      "MO(3)",            "_",            "_",              "_"]
    ],
    [
        ["SHIFTED(Kc1)",   "SHIFTED(Kc2)",    "SHIFTED(Kc3)",           "SHIFTED(Kc4)",           "SHIFTED(Kc5)",        "SHIFTED(Kc6)",   "SHIFTED(Kc7)",    "SHIFTED(Kc8)",  "SHIFTED(Kc9)",    "SHIFTED(Kc0)"],
        ["Kc1",            "Kc2",             "Kc3",                    "Kc4",                    "Kc5",                 "Kc6",            "Kc7",             "Kc8",           "Kc9",             "Kc0"],
        ["F1",             "F2",              "F3",                     "F4",                     "F5",                  "F6",             "F7",              "F8",            "F9",              "F10"],
        ["_",             "_",              "_",                     "_",                      "Space",               "Backspace",      "_",               "_",            "_",              "_"]
   ]
]

[storage]
enabled = true
num_sectors = 32

[behavior.combo]
timeout = "150ms"
combos = [
 { actions = ["K", "L"],         output = "Enter" },
 { actions = ["O", "P"],         output = "Backspace"},
 { actions = ["L", "Semicolon"], output = "Delete"},
 { actions = ["J", "K"],         output = "LCtrl"},
 { actions = ["D", "F"],         output = "LShift"},
 { actions = ["J", "K"],         output = "RShift"}
]


