[keyboard]
name = "TRH34"
product_name = "TRH34"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "TRHKeyboards"
chip = "rp2040"

[matrix]
input_pins = ["PIN_6", "PIN_7", "PIN_8", "PIN_9"]
output_pins = ["PIN_20", "PIN_19", "PIN_18", "PIN_17", "PIN_16", "PIN_15", "PIN_14", "PIN_13", "PIN_12", "PIN_11"]

[layout]
rows = 4 
cols = 10 
layers = 5 
keymap = [
    [    
        ["Q",              "W",                "E",                     "R",                      "T",                   "Y",              "U",                "I",             "O",               "P"],
        ["TH(A-tap, LCtrl-hold)",   "TH(S-tap, LShift-hold)",    "TH(D-tap, LAlt-hold)",           "TH(F-tap, LGui-hold)",             "G",                   "H",              "TH(J-tap, RGui-hold)",     "TH(K-tap, RAlt-hold)",   "TH(L-tap, RShift-hold)",   "TH(Semicolon-tap, RCtrl-hold"],
        ["Z",              "X",                "C",                     "V",                      "B",                   "Quote",          "N",                "M",             "Comma",           "Dot"],
        ["No",             "No",               "No",                    "MO(2)",                  "Space",               "Backspace",      "MO(1)",            "No",            "No",              "No"]
    ],
    [
        ["Escape",         "SHIFTED(Grave)",   "SHIFTED(LeftBracket)",  "SHIFTED(RightBracket)",  "Grave",               "Semicolon",      "LeftBracket",      "RightBracket",  "SHIFTED(Kc9)",    "SHIFTED(Kc0)"],
        ["SHIFTED(Kc1)",   "SHIFTED(Kc2)",     "SHIFTED(Kc3)",          "SHIFTED(Kc4)",           "SHIFTED(Kc5)",        "Minus",          "OSM(RGui)",        "OSM(RAlt)",     "OSM(RShift)",     "OSM(RCtrl)"],
        ["SHIFTED(Kc6)",   "SHIFTED(Kc7)",     "Backslash",             "Slash",                  "SHIFTED(Backslash)",  "Equal",          "SHIFTED(Equal)",  "SHIFTED(Kc8)",  "SHIFTED(Slash)",  "SHIFTED(Kc1)"],
        ["No",             "No",               "No",                    "MO(3)",                  "Space",               "Backspace",      "_",                "No",            "No",              "No"]
    ],
    [
        ["Escape",         "KbMute",          "E",                      "R",                      "No",                  "PageUp",         "Home",             "Up",            "End",             "Delete"],
        ["OSM(LCtrl)",     "OSM(LShift)",     "OSM(LAlt)",              "OSM(LGui)",              "No",                  "Tab",            "Left",             "Down",          "Right",           "Enter"],
        ["KbVolumeDown",   "KbVolumeDown",    "C",                      "V",                      "B",                   "PageDown",       "No",               "No",            "No",              "No"],
        ["No",             "No",              "No",                     "_",                      "Space",               "Backspace",      "MO(3)",            "No",            "No",              "No"]
    ],
    [
        ["Kc1",            "Kc2",             "Kc3",                    "Kc4",                    "Kc5",                 "Kc6",            "Kc7",              "Kc8",           "Kc9",             "Kc0"],
        ["OSM(LCtrl)",     "OSM(LShift)",     "OSM(LAlt)",              "OSM(LGui)",              "F11",                 "F12",            "OSM(RGui)",        "OSM(RAlt)",     "OSM(RShift)",     "OSM(RCtrl)"],
        ["F1",             "F2",              "F3",                     "F4",                     "F5",                  "F6",             "F7",               "F8",            "F9",              "F10"],
        ["No",             "No",              "No",                     "_",                      "Space",               "Backspace",      "_",                "No",            "No",              "No"]
   ]
]

[storage]
enabled = true
num_sectors = 32

[behavior.combo]
timeout = "150ms"
combos = [
 { actions = ["L", "Semicolon"], output = "Enter" },
 { actions = ["O", "P"],         output = "Backspace"},
 { actions = ["I", "P"],         output = "Delete"}
]


